# Generated by Django 6.0.7 on 2026-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcategory_category_image_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='google_map',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
