# Generated by Django 5.2.9 on 2026-08-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_resource_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
