# Generated by Django 5.2.9 on 2026-08-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
