# Generated by Django 5.2.9 on 2026-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='footer_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='navbar_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sidebar_color',
            field=models.CharField(default='#1f2937', max_length=20),
        ),
    ]
