# Generated by Django 5.2.9 on 2026-08-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_usersettings_font_size_usersettings_footer_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='topbar_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
